spring.application.name=spring-learning
spring.datasource.url=jdbc:h2:mem:learningdb
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true